#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 258605445563-edt8122ud7vnggg62fvf0b1l724r2vlj.apps.googleusercontent.com
#            client-secret: r-8exMwZGo8-JBsr8SRouTri

# MySQL

datasource:
  url: jdbc:mysql://localhost:3306/SAVANNAH
  username: root
  password:
  driverClassName: com.mysql.cj.jdbc.Driver
  maxPoolSize: 50
  connectionTimeout: 30000
  idleTimeout: 600000
  maxLifetime: 1800000
  hibernate:
    hbm2ddl.method: validate
    show_sql: false
    format_sql: false
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    timeout: 2000
#  datasource:
#    url: jdbc:mysql://localhost:3306/SAVANNAH
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: none

africastalking:
  apikey: 50c22d4b2df093c3b2df0ba8543a7b7c38dbb572d87de38d6e8f1df2c4a4633e
  username: sandbox


twilio:
  TRIAL_NUMBER: +15153258821
  ACCOUNT_SID: ACa4fbe7dade15481e98d4dea65fb493b0
  AUTH_TOKEN: 28acf5ed41a1117f63d050e9b30e0318


