
server:
  context-path: /savannah
  port: 8085
# MySQ
datasource:
  url: jdbc:mysql://localhost:3306/SAVANNAH
  username: root
  #prod
  password: admin
  #password:
  driverClassName: com.mysql.cj.jdbc.Driver
  maxPoolSize: 50
  connectionTimeout: 30000
  idleTimeout: 600000
  maxLifetime: 1800000
  hibernate:
    hbm2ddl.method: validate
    show_sql: false
    format_sql: false
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    timeout: 2000

africastalking:
  apikey: 50c22d4b2df093c3b2df0ba8543a7b7c38dbb572d87de38d6e8f1df2c4a4633e
  username: sandbox


twilio:
  TRIAL_NUMBER:
  ACCOUNT_SID:
  AUTH_TOKEN:


